// mock data — 假資料
// 照片用 GenerateImage 生成嘅可愛日本女性相（3:4 直向）
const img = (n) => `/${n}.jpg`

export const PROFILES = [
  { id: 'p83', name: 'Yui', age: 26, city: '東涌', occupation: '空姐', tagline: '雲端與紅酒', bio: '國泰長途線空姐，最愛巴黎 layover 同機艙外的日出。下班愛去中環喝一杯 natural wine。期待一個也懂時差、願意等我落地的人。', cover: img('p83'), photos: [img('p83'), img('p83a'), img('p83b')], tags: ['空姐', '飛行', '巴黎', '紅酒', '旅行'], verified: true, stats: { lifestyle: '奢華', budget: '16K+' } },
  { id: 'p84', name: 'Mei', age: 28, city: '九龍站', occupation: '空姐', tagline: '長途線與溫泉', bio: '飛歐洲線五年，最愛倫敦的雨與北海道的溫泉。落地後第一件事是一杯手沖咖啡。尋找一個也懂 jet lag 浪漫的人。', cover: img('p84'), photos: [img('p84'), img('p84a'), img('p84b')], tags: ['空姐', '長途線', '溫泉', '咖啡', '倫敦'], verified: true, stats: { lifestyle: '高端', budget: '18K+' } },
  { id: 'p85', name: 'Saki', age: 25, city: '將軍澳', occupation: '空姐', tagline: '短途線與甜品', bio: '飛日韓短途線，首爾同東京是我的第二個家。最愛機場免稅店的甜點櫃。期待一段也愛周末說走就走的人。', cover: img('p85'), photos: [img('p85'), img('p85a'), img('p85b')], tags: ['空姐', '短途線', '首爾', '甜品', '瑜伽'], verified: false, stats: { lifestyle: '簡約', budget: '10K+' } },
  { id: 'p86', name: 'Riko', age: 30, city: '中環', occupation: '空姐（商務艙）', tagline: '商務艙與米其林', bio: '商務艙乘務長，見盡世界各地的米其林。最愛東京的壽司吧與巴黎的 bistro。尋找一個也懂精緻生活、能一起飛的人。', cover: img('p86'), photos: [img('p86'), img('p86a'), img('p86b')], tags: ['空姐', '商務艙', '米其林', '東京', '滑雪'], verified: true, stats: { lifestyle: '頂級', budget: '25K+' } },
  {
    id: 'p1', name: 'Aria', age: 26, city: '中環', occupation: '藝術策展人', tagline: '喜歡爵士與慢旅行',
    bio: '在畫廊工作，週末愛去赤柱吹海風。重視深度對話多過物質，期待一段彼此啟發的關係。不抽煙，偶爾一杯 natural wine。',
    cover: img('p1'), photos: [img('p1'), img('p1a'), img('p1b')],
    tags: ['藝術', '爵士', '慢旅行', 'Natural Wine', '瑜伽'], verified: true, stats: { lifestyle: '奢華', budget: '8K+' },
  },
  {
    id: 'p2', name: 'Sophia', age: 29, city: '銅鑼灣', occupation: '金融分析師', tagline: '健身與米其林',
    bio: '中環投行，下班後最愛 gym 同 fine dining。尋找成熟、有見識的伴侶，週末飛東京吃壽司是理想約會。',
    cover: img('p2'), photos: [img('p2'), img('p2a'), img('p2b')],
    tags: ['Fine Dining', '健身', '東京', '潛水', '投資'], verified: true, stats: { lifestyle: '高端', budget: '15K+' },
  },
  {
    id: 'p3', name: 'Mira', age: 24, city: '尖沙咀', occupation: '攝影師', tagline: '咖啡與城市散步',
    bio: '自由攝影師，記錄城市的光。喜歡深水埗的舊物與上環的咖啡。期待一段有溫度、彼此支持的關係。',
    cover: img('p3'), photos: [img('p3'), img('p3a'), img('p3b')],
    tags: ['攝影', '咖啡', '深水埗', '電影', '閱讀'], verified: false, stats: { lifestyle: '文青', budget: '5K+' },
  },
  {
    id: 'p4', name: 'Celeste', age: 31, city: '九龍塘', occupation: '創業家', tagline: '紅酒與馬術',
    bio: '經營自家品牌，享受馬術與酒莊週末。欣賞有遠見、懂得生活的伴侶，相信關係是兩個完整的人並肩前行。',
    cover: img('p4'), photos: [img('p4'), img('p4a'), img('p4b')],
    tags: ['創業', '馬術', '紅酒', '酒莊', ' spa'], verified: true, stats: { lifestyle: '頂級', budget: '25K+' },
  },
  {
    id: 'p5', name: 'Yuna', age: 27, city: '沙田', occupation: '鋼琴老師', tagline: '動物義工',
    bio: '教鋼琴，週末做動物義工。個性溫柔但有自己的堅持。理想約會是海邊散步加一頓用心煮的飯。',
    cover: img('p5'), photos: [img('p5'), img('p5a'), img('p5b')],
    tags: ['音樂', '義工', '行山', '素食', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' },
  },
  {
    id: 'p6', name: 'Lena', age: 33, city: '中環', occupation: '律師', tagline: '紅酒與當代藝術',
    bio: '執業律師，收藏當代藝術。享受有質感的對話與安靜的奢華。尋找懂得尊重、能一起成長的伴侶。',
    cover: img('p6'), photos: [img('p6'), img('p6a'), img('p6b')],
    tags: ['藝術收藏', '紅酒', '歌劇', '滑雪', '巴黎'], verified: true, stats: { lifestyle: '奢華', budget: '20K+' },
  },
  {
    id: 'p7', name: 'Hana', age: 25, city: '西貢', occupation: '瑜伽導師', tagline: '冥想與自然生活',
    bio: '教瑜伽六年，相信身體與呼吸是通往內在平靜的門。週末喜歡去西貢行山、赤腳踩沙。期待一段慢下來、彼此傾聽的關係。',
    cover: img('p7'), photos: [img('p7'), img('p7a'), img('p7b')],
    tags: ['瑜伽', '冥想', '行山', '素食', '頌缽'], verified: true, stats: { lifestyle: '簡約', budget: '6K+' },
  },
  {
    id: 'p8', name: 'Emi', age: 28, city: '將軍澳', occupation: '普拉提教練', tagline: '健身與身心平衡',
    bio: '經營自己的普拉提工作室，熱愛把人帶回身體的中線。下班後最愛泡湯與行山。尋找一個也懂得照顧自己的人。',
    cover: img('p8'), photos: [img('p8'), img('p8a'), img('p8b')],
    tags: ['普拉提', '行山', '溫泉', '健康飲食', '閱讀'], verified: false, stats: { lifestyle: '高端', budget: '10K+' },
  },
  {
    id: 'p9', name: 'Sora', age: 26, city: '南丫島', occupation: '茶道與花藝師', tagline: '禪修與慢生活',
    bio: '在南丫島開了一間小茶室，教花藝與茶道。相信美在日常。理想約會是海邊靜坐，然後一起煮一頓簡單的飯。',
    cover: img('p9'), photos: [img('p9'), img('p9a'), img('p9b')],
    tags: ['茶道', '花藝', '禪修', '海邊', '手作'], verified: true, stats: { lifestyle: '文青', budget: '5K+' },
  },
  { id: 'p10', name: 'Miku', age: 23, city: '旺角', occupation: '大學生', tagline: '舞蹈與街頭文化', bio: '主修舞蹈，課餘教 K-pop cover。喜歡旺角的霓虹與深夜糖水舖。期待一段輕鬆、一起大笑的關係。', cover: img('p10'), photos: [img('p10')], tags: ['舞蹈', 'K-pop', '甜品', '攝影', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '3K+' } },
  { id: 'p11', name: 'Rin', age: 27, city: '觀塘', occupation: '平面設計師', tagline: '咖啡與字體設計', bio: '在品牌工作室做視覺設計，週末泡觀塘工廈的咖啡店。欣賞有品味、有自己熱情的人。', cover: img('p11'), photos: [img('p11')], tags: ['設計', '咖啡', '字體', '展覽', '黑膠'], verified: true, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p12', name: 'Yuki', age: 24, city: '中環', occupation: '模特兒', tagline: '時裝與攝影', bio: '自由模特，常飛東京米蘭拍攝。享受時裝週的喧鬧，也愛一個人在酒店泡澡看書。尋找懂欣賞、不佔有的人。', cover: img('p12'), photos: [img('p12')], tags: ['時裝', '攝影', '東京', '紅酒', '閱讀'], verified: true, stats: { lifestyle: '奢華', budget: '18K+' } },
  { id: 'p13', name: 'Mei', age: 29, city: '尖沙咀', occupation: '醫生', tagline: '跑步與健康生活', bio: '公立醫院兒科醫生，下班靠長跑減壓。相信照顧好自己才能照顧別人。期待一段成熟、彼此支持的關係。', cover: img('p13'), photos: [img('p13')], tags: ['跑步', '兒科', '健康', '旅行', '烹飪'], verified: true, stats: { lifestyle: '高端', budget: '20K+' } },
  { id: 'p14', name: 'Aiko', age: 26, city: '太古', occupation: '甜品師', tagline: '烘焙與下午茶', bio: '在高級酒店做甜品，夢想開一間自己的甜品工作室。週末逛花市、試新食譜。理想約會是一起做一個蛋糕。', cover: img('p14'), photos: [img('p14')], tags: ['烘焙', '甜品', '花藝', '下午茶', '法文'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p15', name: 'Nana', age: 25, city: '深水埗', occupation: '插畫家', tagline: '動漫與創作', bio: '全職插畫家，出版過兩本繪本。喜歡深水埗的舊物與黃昏的天台。期待一段能一起安靜創作的關係。', cover: img('p15'), photos: [img('p15')], tags: ['插畫', '繪本', '動漫', '舊物', '貓'], verified: true, stats: { lifestyle: '文青', budget: '5K+' } },
  { id: 'p16', name: 'Riko', age: 30, city: '九龍站', occupation: '建築師', tagline: '旅行與現代設計', bio: '在建築事務所負責公共空間設計。每年去一個新國家看建築。尋找有遠見、懂空間與留白的人。', cover: img('p16'), photos: [img('p16')], tags: ['建築', '旅行', '設計', '攝影', '北歐'], verified: true, stats: { lifestyle: '頂級', budget: '22K+' } },
  { id: 'p17', name: 'Tsubaki', age: 28, city: '上環', occupation: '茶藝師', tagline: '和服與傳統文化', bio: '在茶室教授茶道與和服穿著。相信儀式感是對生活的敬意。理想約會是一場安靜的茶席。', cover: img('p17'), photos: [img('p17')], tags: ['茶道', '和服', '書法', '古典音樂', '京都'], verified: true, stats: { lifestyle: '奢華', budget: '12K+' } },
  { id: 'p18', name: 'Hina', age: 23, city: '大圍', occupation: '護士', tagline: '護理與動物', bio: '急症室護士，下班最愛回家抱貓。個性溫柔但抗壓。期待一個穩重、能讓我安心的人。', cover: img('p18'), photos: [img('p18')], tags: ['護理', '貓', '煲劇', '甜品', '行山'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p19', name: 'Kaede', age: 32, city: '灣仔', occupation: '餐廳老闆', tagline: '美食與酒', bio: '經營一間日法融合餐廳。享受廚房的節奏與客人的笑容。尋找一個也熱愛生活、懂餐桌儀式的人。', cover: img('p19'), photos: [img('p19')], tags: ['美食', '紅酒', '創業', '旅行', '爵士'], verified: true, stats: { lifestyle: '頂級', budget: '30K+' } },
  { id: 'p20', name: 'Saki', age: 26, city: '荔枝角', occupation: '芭蕾舞者', tagline: '舞蹈與藝術', bio: '專業芭蕾舞者，排練之餘愛逛美術館。身體是我的語言。期待一段細膩、彼此尊重節奏的關係。', cover: img('p20'), photos: [img('p20')], tags: ['芭蕾', '美術', '瑜伽', '古典樂', '巴黎'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p21', name: 'Yui', age: 24, city: '數碼港', occupation: '程式設計師', tagline: '科技與貓', bio: '在初創公司做前端工程師。下班寫 side project、養兩隻貓。尋找一個也對世界好奇的人。', cover: img('p21'), photos: [img('p21')], tags: ['編程', '貓', '科幻', '桌遊', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '8K+' } },
  { id: 'p22', name: 'Mio', age: 29, city: '中環', occupation: '調酒師', tagline: '雞尾酒與深夜', bio: '在隱藏酒吧調酒，喜歡聽陌生人的故事。下班沿著海邊走回家。期待一段有溫度、不怕沉默的關係。', cover: img('p22'), photos: [img('p22')], tags: ['調酒', '爵士', '深夜', '威士忌', '電影'], verified: true, stats: { lifestyle: '高端', budget: '9K+' } },
  { id: 'p23', name: 'Rina', age: 27, city: '東涌', occupation: '旅遊博主', tagline: '旅行與攝影', bio: '全職旅遊博主，去過 40 個國家。相信最好的紀念品是回憶。尋找一個也願意出發的人。', cover: img('p23'), photos: [img('p23')], tags: ['旅行', '攝影', '露營', '潛水', '寫作'], verified: true, stats: { lifestyle: '奢華', budget: '14K+' } },
  { id: 'p24', name: 'Ayame', age: 25, city: '銅鑼灣', occupation: '調香師', tagline: '香氣與美學', bio: '為品牌調製香水，相信氣味是記憶的鑰匙。週末逛花市、收集老香水瓶。理想約會是一起聞一場雨。', cover: img('p24'), photos: [img('p24')], tags: ['香水', '花藝', '古董', '詩', '法式'], verified: false, stats: { lifestyle: '奢華', budget: '10K+' } },
  { id: 'p25', name: 'Koharu', age: 31, city: '香港大學', occupation: '大學講師', tagline: '文學與咖啡', bio: '教近代文學，研究女性書寫。喜歡圖書館的氣味與深夜的咖啡。尋找一段能深度對話的關係。', cover: img('p25'), photos: [img('p25')], tags: ['文學', '咖啡', '電影', '古典樂', '京都'], verified: true, stats: { lifestyle: '文青', budget: '13K+' } },
  { id: 'p26', name: 'Shiori', age: 26, city: '粉嶺', occupation: '園藝師', tagline: '植物與自然', bio: '在植物園工作，週末經營自己的小溫室。相信慢就是快。期待一段一起種點什麼的關係。', cover: img('p26'), photos: [img('p26')], tags: ['植物', '溫室', '行山', '素食', '陶藝'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p27', name: 'Hinata', age: 23, city: '將軍澳', occupation: '偶像練習生', tagline: '唱歌與舞台', bio: '在娛樂公司受訓三年，夢想站上紅館。生活是練習與等待。尋找一個相信我、也讓我相信的人。', cover: img('p27'), photos: [img('p27')], tags: ['唱歌', '舞蹈', '舞台', '時尚', '甜品'], verified: false, stats: { lifestyle: '高端', budget: '6K+' } },
  { id: 'p28', name: 'Asuka', age: 30, city: '奧運', occupation: '物理治療師', tagline: '運動與康復', bio: '在運動康復診所工作，幫運動員重返賽場。週末教跑步班。期待一段健康、一起向前跑的關係。', cover: img('p28'), photos: [img('p28')], tags: ['物理治療', '跑步', '健身', '健康飲食', '行山'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p29', name: 'Kanna', age: 28, city: '火炭', occupation: '陶藝家', tagline: '手作與慢活', bio: '在火炭工作室做陶藝，辦過三次個展。相信手作的溫度。理想約會是一起捏一個碗。', cover: img('p29'), photos: [img('p29')], tags: ['陶藝', '手作', '茶道', '素食', '貓'], verified: true, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p30', name: 'Fumiko', age: 33, city: '九龍塘', occupation: '翻譯員', tagline: '語言與文學', bio: '日英中三語翻譯，譯過十本小說。享受文字的精準與曖昧。尋找一段安靜、彼此理解的關係。', cover: img('p30'), photos: [img('p30')], tags: ['翻譯', '文學', '紅酒', '歌劇', '旅行'], verified: true, stats: { lifestyle: '奢華', budget: '16K+' } },
  { id: 'p31', name: 'Chiho', age: 25, city: '西貢', occupation: '潛水教練', tagline: '海洋與冒險', bio: 'PADI 教練，最愛西貢海底的珊瑚。週末帶學員下水。期待一段不怕深、也敢一起冒險的關係。', cover: img('p31'), photos: [img('p31')], tags: ['潛水', '海洋', '衝浪', '旅行', '攝影'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p32', name: 'Nazuna', age: 27, city: '大坑', occupation: '麵包師', tagline: '烘焙與清晨', bio: '凌晨四點開工的麵包師，最愛看客人咬下第一口。週末睡到中午。尋找一個懂清晨與麵包香的人。', cover: img('p32'), photos: [img('p32')], tags: ['烘焙', '咖啡', '清晨', '單車', '爵士'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p33', name: 'Sayuri', age: 29, city: '紅磡', occupation: '鋼琴家', tagline: '音樂與演出', bio: '交響樂團鋼琴手，巡演過歐亞。舞台之外愛一個人煮麵。期待一段懂休止符的關係。', cover: img('p33'), photos: [img('p33')], tags: ['鋼琴', '古典樂', '歌劇', '紅酒', '巴黎'], verified: true, stats: { lifestyle: '奢華', budget: '19K+' } },
  { id: 'p34', name: 'Wakana', age: 24, city: '黃竹坑', occupation: '時尚模特', tagline: '街頭與攝影', bio: '街頭風模特，常出現在南區的塗鴉牆前。享受被拍的瞬間。尋找一個也敢穿、敢活的人。', cover: img('p34'), photos: [img('p34')], tags: ['時尚', '街拍', '滑板', '音樂節', '咖啡'], verified: false, stats: { lifestyle: '文青', budget: '8K+' } },
  { id: 'p35', name: 'Azumi', age: 32, city: '康城', occupation: '營養師', tagline: '健康與身心', bio: '註冊營養師，教人吃出平衡。自己最愛綠色果昔與海邊散步。期待一段一起好好吃飯的關係。', cover: img('p35'), photos: [img('p35')], tags: ['營養', '果昔', '瑜伽', '行山', '素食'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p36', name: 'Emiri', age: 26, city: '太子', occupation: '花店店主', tagline: '花藝與日常', bio: '在花墟開花店，相信花是日常的詩。週末辦花藝工作坊。理想約會是一起逛花市、回家插一瓶。', cover: img('p36'), photos: [img('p36')], tags: ['花藝', '花店', '咖啡', '甜點', '攝影'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p37', name: 'Ruka', age: 23, city: '深水埗', occupation: '咖啡師', tagline: '拉花與音樂', bio: '在獨立咖啡店做吧台，拉花是我的簽名。下班玩 bass、逛唱片行。尋找一個也懂深夜咖啡的人。', cover: img('p37'), photos: [img('p37')], tags: ['咖啡', '拉花', '音樂', '黑膠', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p38', name: 'Shino', age: 30, city: '佐敦', occupation: '中醫師', tagline: '針灸與養生', bio: '註冊中醫，擅長針灸與養生。相信身體是時間的記錄。期待一段慢條理、彼此調理的關係。', cover: img('p38'), photos: [img('p38')], tags: ['中醫', '針灸', '養生', '太極', '茶道'], verified: true, stats: { lifestyle: '高端', budget: '13K+' } },
  { id: 'p39', name: 'Tsumugi', age: 28, city: '鑽石山', occupation: '和服模特', tagline: '傳統與美學', bio: '兼職和服模特，志業是日本傳統文化。週末在志蓮淨苑散步。尋找一個也懂靜與美的人。', cover: img('p39'), photos: [img('p39')], tags: ['和服', '傳統', '茶道', '紅葉', '京都'], verified: true, stats: { lifestyle: '奢華', budget: '15K+' } },
  { id: 'p40', name: 'Suzu', age: 22, city: '大埔', occupation: '美術學生', tagline: '繪畫與公園', bio: '在讀美術系，最愛在大埔海濱公園畫水彩。相信創作是最好的傾訴。期待一段一起安靜看光的關係。', cover: img('p40'), photos: [img('p40')], tags: ['繪畫', '水彩', '公園', '貓', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '3K+' } },
  { id: 'p41', name: 'Akane', age: 27, city: '尖沙咀', occupation: '壽司師傅', tagline: '江戶前與清酒', bio: '在壽司店做板前，是店裡少見的女師傅。享受刀工的精準與節奏。尋找一個也懂職人精神的人。', cover: img('p41'), photos: [img('p41')], tags: ['壽司', '清酒', '職人', '旅行', '爵士'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p42', name: 'Riko', age: 26, city: '九龍塘', occupation: '網球手', tagline: '運動與陽光', bio: '半職業網球手，週末教小朋友打球。最愛陽光與流汗的痛快。期待一段健康、一起出汗的關係。', cover: img('p42'), photos: [img('p42')], tags: ['網球', '運動', '陽光', '健康', '旅行'], verified: false, stats: { lifestyle: '高端', budget: '9K+' } },
  { id: 'p43', name: 'Yume', age: 29, city: '黃竹坑', occupation: '珠寶設計師', tagline: '寶石與手作', bio: '在工作室做高訂珠寶，每件都是獨一無二。相信細節是愛。理想約會是一起挑一顆石頭。', cover: img('p43'), photos: [img('p43')], tags: ['珠寶', '寶石', '手作', '美術', '紅酒'], verified: true, stats: { lifestyle: '奢華', budget: '17K+' } },
  { id: 'p44', name: 'Hinako', age: 24, city: '將軍澳', occupation: '牙齒衛生員', tagline: '笑容與健康', bio: '在牙科診所工作，最愛看見客人自信笑。下班愛逛烘焙材料店。尋找一個也愛笑的人。', cover: img('p44'), photos: [img('p44')], tags: ['牙科', '笑容', '烘焙', '貓', '行山'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p45', name: 'Miyu', age: 25, city: '尖沙咀', occupation: '髮型師', tagline: '造型與美感', bio: '在髮廊做造型師，最愛幫客人找到適合自己的樣子。下班逛化妝品店、試新色。期待一段一起變靚的關係。', cover: img('p45'), photos: [img('p45')], tags: ['髮型', '美妝', '時尚', '咖啡', '音樂'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p46', name: 'Sakura', age: 28, city: '上環', occupation: '小說家', tagline: '文字與深夜', bio: '全職寫作，出版過三本短篇集。最愛凌晨三點的咖啡與打字聲。尋找一個願意做我第一個讀者的人。', cover: img('p46'), photos: [img('p46')], tags: ['寫作', '文學', '咖啡', '電影', '貓'], verified: true, stats: { lifestyle: '文青', budget: '8K+' } },
  { id: 'p47', name: 'Noa', age: 23, city: '大埔', occupation: '單車手', tagline: '速度與風', bio: '半職業公路單車手，週末踩吐露港。享受風在耳邊的聲音。期待一段一起出發、不怕遠的關係。', cover: img('p47'), photos: [img('p47')], tags: ['單車', '公路', '旅行', '健康', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p48', name: 'Rei', age: 30, city: '黃竹坑', occupation: '畫廊總監', tagline: '當代藝術與酒', bio: '經營一間當代藝術畫廊，策劃過二十場展覽。享受開幕酒會的喧鬧，也愛閉館後的安靜。尋找一個也懂留白的人。', cover: img('p48'), photos: [img('p48')], tags: ['藝術', '策展', '紅酒', '旅行', '設計'], verified: true, stats: { lifestyle: '奢華', budget: '18K+' } },
  { id: 'p49', name: 'Tama', age: 26, city: '太子', occupation: '寵物美容師', tagline: '毛孩與日常', bio: '在寵物沙龍幫毛孩造型，最愛看主人接走時的笑容。養了三隻貓。期待一段也愛動物的關係。', cover: img('p49'), photos: [img('p49')], tags: ['寵物', '貓', '美容', '行山', '甜點'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p50', name: 'Aoi', age: 29, city: '淺水灣', occupation: 'Spa 治療師', tagline: '身心與香氣', bio: '在高級 spa 做芳療師，相信觸碰是療癒的開始。下班愛海邊散步與冥想。尋找一段慢下來的關係。', cover: img('p50'), photos: [img('p50')], tags: ['spa', '芳療', '冥想', '海邊', '瑜伽'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p51', name: 'Kotori', age: 27, city: '灣仔', occupation: '室內設計師', tagline: '空間與光影', bio: '在設計公司做住宅項目，相信家是人的延伸。週末逛傢俬店與咖啡店。理想約會是一起逛一間樣板屋。', cover: img('p51'), photos: [img('p51')], tags: ['設計', '空間', '咖啡', '旅行', '北歐'], verified: true, stats: { lifestyle: '高端', budget: '13K+' } },
  { id: 'p52', name: 'Hanae', age: 22, city: '中環', occupation: '音樂節策劃', tagline: '電子與日落', bio: '在活動公司做音樂節策劃，最愛日落時分的舞台。生活是耳機與背包。尋找一個也敢跳進人群的人。', cover: img('p52'), photos: [img('p52')], tags: ['音樂節', '電子', '旅行', '攝影', '街頭'], verified: false, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p53', name: 'Sumire', age: 30, city: '太古', occupation: '書店店主', tagline: '閱讀與咖啡', bio: '經營一間獨立書店兼咖啡館，相信書是另一種陪伴。週末辦讀書會。理想約會是一起讀一本書的下午。', cover: img('p53'), photos: [img('p53')], tags: ['書店', '閱讀', '咖啡', '詩', '貓'], verified: true, stats: { lifestyle: '文青', budget: '9K+' } },
  { id: 'p54', name: 'Mizuki', age: 24, city: '西貢', occupation: '生態攝影師', tagline: '濕地與候鳥', bio: '專拍香港濕地與候鳥，凌晨蹲點是日常。相信耐心是看見美的條件。期待一段也願意等的人。', cover: img('p54'), photos: [img('p54')], tags: ['攝影', '生態', '行山', '觀鳥', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p55', name: 'Yuna', age: 26, city: '上環', occupation: '咖啡店店主', tagline: '拿鐵與午後光', bio: '在上環開了一間小咖啡店，最愛下午三點斜陽照進窗的時刻。相信一杯咖啡可以改變一天。期待一段也懂慢下來的人。', cover: img('p55'), photos: [img('p55')], tags: ['咖啡', '拿鐵', '閱讀', '貓', '甜點'], verified: false, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p56', name: 'Kurumi', age: 24, city: '佐敦', occupation: '復古服裝店主', tagline: '古著與老歌', bio: '在佐敦開古著店，專收 70 年代歐洲洋裝。下班聽黑膠、寫明信片。尋找一個也愛舊物的人。', cover: img('p56'), photos: [img('p56')], tags: ['古著', '黑膠', '復古', '電影', '旅行'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p57', name: 'Tsubasa', age: 29, city: '觀塘', occupation: '精釀啤酒師', tagline: '麥芽與深夜', bio: '在觀塘工廈做精釀啤酒，最愛試新配方。下班沿海邊跑步。期待一段也敢嘗試的人。', cover: img('p57'), photos: [img('p57')], tags: ['精釀', '啤酒', '跑步', '音樂', '旅行'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p58', name: 'Momo', age: 22, city: '旺角', occupation: '滑板店店員', tagline: '街頭與塗鴉', bio: '在滑板店打工，下班去工廈滑板。染髮是心情的記錄。期待一段一起瘟狂的人。', cover: img('p58'), photos: [img('p58')], tags: ['滑板', '街頭', '塗鴉', '音樂', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '3K+' } },
  { id: 'p59', name: 'Ayaka', age: 27, city: '灣仔', occupation: '現代舞者', tagline: '身體與呼吸', bio: '在舞團跳現代舞，最愛排練室午後的光。相信身體比語言誠實。期待一段也懂沉默的人。', cover: img('p59'), photos: [img('p59')], tags: ['舞蹈', '現代舞', '瑜伽', '音樂', '美術'], verified: true, stats: { lifestyle: '高端', budget: '10K+' } },
  { id: 'p60', name: 'Ruka', age: 25, city: '油麻地', occupation: '塔羅占卜師', tagline: '星象與香氣', bio: '在油麻地開占卜室，用塔羅與星象幫人看見自己。相信直覺是另一種理性。期待一段也願意探索內在的人。', cover: img('p60'), photos: [img('p60')], tags: ['塔羅', '占星', '香氣', '冥想', '古董'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p61', name: 'Haruka', age: 30, city: '火炭', occupation: '咖啡烘焙師', tagline: '豆與火候', bio: '在火炭工作室烘豆，為本地咖啡店供豆。享受烘豆機的聲音與香氣。尋找一個也懂專注的人。', cover: img('p61'), photos: [img('p61')], tags: ['咖啡', '烘豆', '閱讀', '單車', '黑膠'], verified: true, stats: { lifestyle: '高端', budget: '13K+' } },
  { id: 'p62', name: 'Nanami', age: 23, city: '大圍', occupation: '街頭歌手', tagline: '吉他與黃昏', bio: '在街頭彈唱，也接小型商演。最愛黃昏時分的海邊。理想約會是一起寫一首歌。', cover: img('p62'), photos: [img('p62')], tags: ['音樂', '吉他', '街頭', '旅行', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p63', name: 'Shizuku', age: 28, city: '中環', occupation: '珠寶鑑定師', tagline: '寶石與光', bio: '在拍賣行做珠寶鑑定，見過世上最貴的石頭。享受安靜的奢華。尋找一個也懂細節的人。', cover: img('p63'), photos: [img('p63')], tags: ['珠寶', '鑑定', '紅酒', '歌劇', '巴黎'], verified: true, stats: { lifestyle: '奢華', budget: '20K+' } },
  { id: 'p64', name: 'Hina', age: 26, city: '東涌', occupation: '滑雪教練', tagline: '雪與速度', bio: '冬天去日本教滑雪，夏天在香港教滑水。享受風在臉上的感覺。期待一段也愛出發的人。', cover: img('p64'), photos: [img('p64')], tags: ['滑雪', '旅行', '運動', '北海道', '咖啡'], verified: false, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p65', name: 'Chika', age: 24, city: '深水埗', occupation: '漫畫家', tagline: '線稿與深夜', bio: '連載少女漫畫三年，最愛截稿後的拉麵。養一隻叫墨水的貓。期待一段也懂創作孤獨的人。', cover: img('p65'), photos: [img('p65')], tags: ['漫畫', '繪畫', '貓', '拉麵', '電影'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p66', name: 'Akira', age: 29, city: '中環', occupation: '米其林副廚', tagline: '爐火與節奏', bio: '在米其林餐廳做副廚，享受廚房的節奏與壓力。下班愛一個人吃碗雲吞。期待一段也懂專注的人。', cover: img('p66'), photos: [img('p66')], tags: ['料理', '美食', '紅酒', '旅行', '爵士'], verified: true, stats: { lifestyle: '奢華', budget: '18K+' } },
  { id: 'p67', name: 'Yuzu', age: 22, city: '觀塘', occupation: '街舞舞者', tagline: '節拍與霓虹', bio: '在舞團跳 hip-hop，週末 busking。最愛觀塘海濱的夜晚。期待一段也敢跳出自己的人。', cover: img('p67'), photos: [img('p67')], tags: ['街舞', '音樂', '霓虹', '旅行', '甜點'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p68', name: 'Saki', age: 27, city: '銅鑼灣', occupation: '美容顧問', tagline: '香氣與保養', bio: '在高級化妝品櫃做美容顧問，最愛幫客人找到適合的香。下班逛花市。期待一段也懂照顧自己的人。', cover: img('p68'), photos: [img('p68')], tags: ['美容', '香水', '花藝', '瑜伽', '下午茶'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p69', name: 'Towa', age: 25, city: '荔枝角', occupation: '攀岩教練', tagline: '岩壁與專注', bio: '在室內攀石館做教練，最愛解決路線的瞬間。享受身體與牆的對話。期待一段也愛挑戰的人。', cover: img('p69'), photos: [img('p69')], tags: ['攀岩', '運動', '行山', '咖啡', '旅行'], verified: false, stats: { lifestyle: '簡約', budget: '6K+' } },
  { id: 'p70', name: 'Kaori', age: 30, city: '中環', occupation: '企業律師', tagline: '合約與紅酒', bio: '在律師行做商業訴訟，下班靠紅酒與歌劇減壓。享受有質感的對話。尋找一個也懂安靜奢華的人。', cover: img('p70'), photos: [img('p70')], tags: ['法律', '紅酒', '歌劇', '藝術', '巴黎'], verified: true, stats: { lifestyle: '頂級', budget: '25K+' } },
  { id: 'p71', name: 'Rima', age: 23, city: '將軍澳', occupation: '生活博主', tagline: '鏡頭與日常', bio: '全職生活博主，分享穿搭與咖啡。享受拍片的過程多過成果。期待一段也懂分享的人。', cover: img('p71'), photos: [img('p71')], tags: ['博主', '時尚', '咖啡', '旅行', '甜點'], verified: true, stats: { lifestyle: '奢華', budget: '14K+' } },
  { id: 'p72', name: 'Wakaba', age: 28, city: '鑽石山', occupation: '茶道老師', tagline: '抹茶與四季', bio: '在茶室教授茶道，相信儀式是對時間的敬意。最愛秋天的紅葉。理想約會是一場安靜的茶席。', cover: img('p72'), photos: [img('p72')], tags: ['茶道', '抹茶', '和服', '書法', '京都'], verified: true, stats: { lifestyle: '奢華', budget: '13K+' } },
  { id: 'p73', name: 'Himari', age: 26, city: '西貢', occupation: '戶外攝影師', tagline: '山海與底片', bio: '專拍香港山海，用底片記錄。最愛西貢的清晨。期待一段也願意走到戶外的人。', cover: img('p73'), photos: [img('p73')], tags: ['攝影', '底片', '行山', '海邊', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '6K+' } },
  { id: 'p74', name: 'Koko', age: 24, city: '太子', occupation: '甜品博主', tagline: '糖霜與鏡頭', bio: '經營甜品頻道，每週試新食譜。最愛粉色與奶油。期待一段也愛甜的人。', cover: img('p74'), photos: [img('p74')], tags: ['甜品', '烘焙', '粉色', '貓', '下午茶'], verified: false, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p75', name: 'Sana', age: 27, city: '中環', occupation: '瑜伽導師', tagline: '呼吸與身心靈', bio: '教瑜伽八年，相信呼吸是回到自己的路。最愛清晨的陽光與一張好墊。期待一段也願意慢下來的人。', cover: img('p75'), photos: [img('p75'), img('p75a'), img('p75b')], tags: ['瑜伽', '冥想', '身心靈', '綠色果昔', '行山'], verified: true, stats: { lifestyle: '簡約', budget: '8K+' } },
  { id: 'p76', name: 'Mio', age: 25, city: '西貢', occupation: '瑜伽導師', tagline: '竹與自然', bio: '在竹舍工作室教瑜伽，週末帶戶外課。享受風穿過竹葉的聲音。期待一段也愛自然的人。', cover: img('p76'), photos: [img('p76'), img('p76a'), img('p76b')], tags: ['瑜伽', '竹', '自然', '咖啡', '行山'], verified: false, stats: { lifestyle: '簡約', budget: '6K+' } },
  { id: 'p77', name: 'Rina', age: 29, city: '灣仔', occupation: '瑜伽導師', tagline: '日落與天台', bio: '在天台教黃昏瑜伽，最愛城市與夕陽的交界。相信身體是時間的記錄。期待一段也懂黃昏的人。', cover: img('p77'), photos: [img('p77'), img('p77a'), img('p77b')], tags: ['瑜伽', '天台', '日落', '閱讀', '紅酒'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p78', name: 'Yuna', age: 24, city: '將軍澳', occupation: '瑜伽導師', tagline: '植物與晨光', bio: '在家工作室教瑜伽，屋企種滿植物。最愛早晨的光與澆水的瞬間。期待一段也愛綠色的人。', cover: img('p78'), photos: [img('p78'), img('p78a'), img('p78b')], tags: ['瑜伽', '植物', '晨光', '甜點', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p79', name: 'Hana', age: 28, city: '大坑', occupation: '瑜伽導師', tagline: '花園與靜心', bio: '在花園露台教瑜伽，下課愛去附近咖啡店。享受靜與動的平衡。期待一段也懂留白的人。', cover: img('p79'), photos: [img('p79'), img('p79a'), img('p79b')], tags: ['瑜伽', '花園', '咖啡', '身心靈', '閱讀'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p80', name: 'Airi', age: 26, city: '淺水灣', occupation: '瑜伽導師', tagline: '海邊與呼吸', bio: '在海邊教晨瑜伽，最愛浪聲與呼吸的節奏。下班愛行沙灘。期待一段也願意走到戶外的人。', cover: img('p80'), photos: [img('p80'), img('p80a'), img('p80b')], tags: ['瑜伽', '海邊', '晨光', '身心靈', '果昔'], verified: false, stats: { lifestyle: '簡約', budget: '7K+' } },
  { id: 'p81', name: 'Tsumugi', age: 23, city: '沙田', occupation: '瑜伽導師', tagline: '山與清新', bio: '在山邊教瑜伽，最愛吐露港的清晨。享受風在臉上的感覺。期待一段也愛出發的人。', cover: img('p81'), photos: [img('p81'), img('p81a'), img('p81b')], tags: ['瑜伽', '山', '自然', '咖啡', '旅行'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p82', name: 'Koharu', age: 25, city: '上環', occupation: '瑜伽導師', tagline: '白與靜', bio: '在白色工作室教瑜伽，相信空是另一種滿。下課愛一杯茶與一本書。期待一段也懂安靜的人。', cover: img('p82'), photos: [img('p82'), img('p82a'), img('p82b')], tags: ['瑜伽', '茶', '閱讀', '身心靈', '貓'], verified: true, stats: { lifestyle: '文青', budget: '9K+' } },
]

export const FILTERS = ['全部', '奢華', '高端', '文青', '頂級', '簡約']
