// mock data — 假資料
// 照片用 GenerateImage 生成嘅可愛日本女性相（3:4 直向）
const img = (n) => `/${n}.jpg`

export const PROFILES = [
  {
    id: 'p1', name: 'Aria', age: 26, city: '中環', occupation: '藝術策展人', tagline: '喜歡爵士與慢旅行',
    bio: '在畫廊工作，週末愛去赤柱吹海風。重視深度對話多過物質，期待一段彼此啟發的關係。不抽煙，偶爾一杯 natural wine。',
    cover: img('p1'), photos: [img('p1'), img('p1a'), img('p1b')],
    tags: ['藝術', '爵士', '慢旅行', 'Natural Wine', '瑜伽'], verified: true, stats: { lifestyle: '奢華', budget: '8K+' },
  },
  {
    id: 'p2', name: 'Sophia', age: 29, city: '銅鑼灣', occupation: '金融分析師', tagline: '健身與米其林',
    bio: '中環投行，下班後最愛 gym 同 fine dining。尋找成熟、有見識的伴侶，週末飛東京吃壽司是理想約會。',
    cover: img('p2'), photos: [img('p2'), img('p2a'), img('p2b')],
    tags: ['Fine Dining', '健身', '東京', '潛水', '投資'], verified: true, stats: { lifestyle: '高端', budget: '15K+' },
  },
  {
    id: 'p3', name: 'Mira', age: 24, city: '尖沙咀', occupation: '攝影師', tagline: '咖啡與城市散步',
    bio: '自由攝影師，記錄城市的光。喜歡深水埗的舊物與上環的咖啡。期待一段有溫度、彼此支持的關係。',
    cover: img('p3'), photos: [img('p3'), img('p3a'), img('p3b')],
    tags: ['攝影', '咖啡', '深水埗', '電影', '閱讀'], verified: false, stats: { lifestyle: '文青', budget: '5K+' },
  },
  {
    id: 'p4', name: 'Celeste', age: 31, city: '九龍塘', occupation: '創業家', tagline: '紅酒與馬術',
    bio: '經營自家品牌，享受馬術與酒莊週末。欣賞有遠見、懂得生活的伴侶，相信關係是兩個完整的人並肩前行。',
    cover: img('p4'), photos: [img('p4'), img('p4a'), img('p4b')],
    tags: ['創業', '馬術', '紅酒', '酒莊', ' spa'], verified: true, stats: { lifestyle: '頂級', budget: '25K+' },
  },
  {
    id: 'p5', name: 'Yuna', age: 27, city: '沙田', occupation: '鋼琴老師', tagline: '動物義工',
    bio: '教鋼琴，週末做動物義工。個性溫柔但有自己的堅持。理想約會是海邊散步加一頓用心煮的飯。',
    cover: img('p5'), photos: [img('p5'), img('p5a'), img('p5b')],
    tags: ['音樂', '義工', '行山', '素食', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' },
  },
  {
    id: 'p6', name: 'Lena', age: 33, city: '中環', occupation: '律師', tagline: '紅酒與當代藝術',
    bio: '執業律師，收藏當代藝術。享受有質感的對話與安靜的奢華。尋找懂得尊重、能一起成長的伴侶。',
    cover: img('p6'), photos: [img('p6'), img('p6a'), img('p6b')],
    tags: ['藝術收藏', '紅酒', '歌劇', '滑雪', '巴黎'], verified: true, stats: { lifestyle: '奢華', budget: '20K+' },
  },
  {
    id: 'p7', name: 'Hana', age: 25, city: '西貢', occupation: '瑜伽導師', tagline: '冥想與自然生活',
    bio: '教瑜伽六年，相信身體與呼吸是通往內在平靜的門。週末喜歡去西貢行山、赤腳踩沙。期待一段慢下來、彼此傾聽的關係。',
    cover: img('p7'), photos: [img('p7'), img('p7a'), img('p7b')],
    tags: ['瑜伽', '冥想', '行山', '素食', '頌缽'], verified: true, stats: { lifestyle: '簡約', budget: '6K+' },
  },
  {
    id: 'p8', name: 'Emi', age: 28, city: '將軍澳', occupation: '普拉提教練', tagline: '健身與身心平衡',
    bio: '經營自己的普拉提工作室，熱愛把人帶回身體的中線。下班後最愛泡湯與行山。尋找一個也懂得照顧自己的人。',
    cover: img('p8'), photos: [img('p8'), img('p8a'), img('p8b')],
    tags: ['普拉提', '行山', '溫泉', '健康飲食', '閱讀'], verified: false, stats: { lifestyle: '高端', budget: '10K+' },
  },
  {
    id: 'p9', name: 'Sora', age: 26, city: '南丫島', occupation: '茶道與花藝師', tagline: '禪修與慢生活',
    bio: '在南丫島開了一間小茶室，教花藝與茶道。相信美在日常。理想約會是海邊靜坐，然後一起煮一頓簡單的飯。',
    cover: img('p9'), photos: [img('p9'), img('p9a'), img('p9b')],
    tags: ['茶道', '花藝', '禪修', '海邊', '手作'], verified: true, stats: { lifestyle: '文青', budget: '5K+' },
  },
  { id: 'p10', name: 'Miku', age: 23, city: '旺角', occupation: '大學生', tagline: '舞蹈與街頭文化', bio: '主修舞蹈，課餘教 K-pop cover。喜歡旺角的霓虹與深夜糖水舖。期待一段輕鬆、一起大笑的關係。', cover: img('p10'), photos: [img('p10')], tags: ['舞蹈', 'K-pop', '甜品', '攝影', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '3K+' } },
  { id: 'p11', name: 'Rin', age: 27, city: '觀塘', occupation: '平面設計師', tagline: '咖啡與字體設計', bio: '在品牌工作室做視覺設計，週末泡觀塘工廈的咖啡店。欣賞有品味、有自己熱情的人。', cover: img('p11'), photos: [img('p11')], tags: ['設計', '咖啡', '字體', '展覽', '黑膠'], verified: true, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p12', name: 'Yuki', age: 24, city: '中環', occupation: '模特兒', tagline: '時裝與攝影', bio: '自由模特，常飛東京米蘭拍攝。享受時裝週的喧鬧，也愛一個人在酒店泡澡看書。尋找懂欣賞、不佔有的人。', cover: img('p12'), photos: [img('p12')], tags: ['時裝', '攝影', '東京', '紅酒', '閱讀'], verified: true, stats: { lifestyle: '奢華', budget: '18K+' } },
  { id: 'p13', name: 'Mei', age: 29, city: '尖沙咀', occupation: '醫生', tagline: '跑步與健康生活', bio: '公立醫院兒科醫生，下班靠長跑減壓。相信照顧好自己才能照顧別人。期待一段成熟、彼此支持的關係。', cover: img('p13'), photos: [img('p13')], tags: ['跑步', '兒科', '健康', '旅行', '烹飪'], verified: true, stats: { lifestyle: '高端', budget: '20K+' } },
  { id: 'p14', name: 'Aiko', age: 26, city: '太古', occupation: '甜品師', tagline: '烘焙與下午茶', bio: '在高級酒店做甜品，夢想開一間自己的甜品工作室。週末逛花市、試新食譜。理想約會是一起做一個蛋糕。', cover: img('p14'), photos: [img('p14')], tags: ['烘焙', '甜品', '花藝', '下午茶', '法文'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p15', name: 'Nana', age: 25, city: '深水埗', occupation: '插畫家', tagline: '動漫與創作', bio: '全職插畫家，出版過兩本繪本。喜歡深水埗的舊物與黃昏的天台。期待一段能一起安靜創作的關係。', cover: img('p15'), photos: [img('p15')], tags: ['插畫', '繪本', '動漫', '舊物', '貓'], verified: true, stats: { lifestyle: '文青', budget: '5K+' } },
  { id: 'p16', name: 'Riko', age: 30, city: '九龍站', occupation: '建築師', tagline: '旅行與現代設計', bio: '在建築事務所負責公共空間設計。每年去一個新國家看建築。尋找有遠見、懂空間與留白的人。', cover: img('p16'), photos: [img('p16')], tags: ['建築', '旅行', '設計', '攝影', '北歐'], verified: true, stats: { lifestyle: '頂級', budget: '22K+' } },
  { id: 'p17', name: 'Tsubaki', age: 28, city: '上環', occupation: '茶藝師', tagline: '和服與傳統文化', bio: '在茶室教授茶道與和服穿著。相信儀式感是對生活的敬意。理想約會是一場安靜的茶席。', cover: img('p17'), photos: [img('p17')], tags: ['茶道', '和服', '書法', '古典音樂', '京都'], verified: true, stats: { lifestyle: '奢華', budget: '12K+' } },
  { id: 'p18', name: 'Hina', age: 23, city: '大圍', occupation: '護士', tagline: '護理與動物', bio: '急症室護士，下班最愛回家抱貓。個性溫柔但抗壓。期待一個穩重、能讓我安心的人。', cover: img('p18'), photos: [img('p18')], tags: ['護理', '貓', '煲劇', '甜品', '行山'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p19', name: 'Kaede', age: 32, city: '灣仔', occupation: '餐廳老闆', tagline: '美食與酒', bio: '經營一間日法融合餐廳。享受廚房的節奏與客人的笑容。尋找一個也熱愛生活、懂餐桌儀式的人。', cover: img('p19'), photos: [img('p19')], tags: ['美食', '紅酒', '創業', '旅行', '爵士'], verified: true, stats: { lifestyle: '頂級', budget: '30K+' } },
  { id: 'p20', name: 'Saki', age: 26, city: '荔枝角', occupation: '芭蕾舞者', tagline: '舞蹈與藝術', bio: '專業芭蕾舞者，排練之餘愛逛美術館。身體是我的語言。期待一段細膩、彼此尊重節奏的關係。', cover: img('p20'), photos: [img('p20')], tags: ['芭蕾', '美術', '瑜伽', '古典樂', '巴黎'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p21', name: 'Yui', age: 24, city: '數碼港', occupation: '程式設計師', tagline: '科技與貓', bio: '在初創公司做前端工程師。下班寫 side project、養兩隻貓。尋找一個也對世界好奇的人。', cover: img('p21'), photos: [img('p21')], tags: ['編程', '貓', '科幻', '桌遊', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '8K+' } },
  { id: 'p22', name: 'Mio', age: 29, city: '中環', occupation: '調酒師', tagline: '雞尾酒與深夜', bio: '在隱藏酒吧調酒，喜歡聽陌生人的故事。下班沿著海邊走回家。期待一段有溫度、不怕沉默的關係。', cover: img('p22'), photos: [img('p22')], tags: ['調酒', '爵士', '深夜', '威士忌', '電影'], verified: true, stats: { lifestyle: '高端', budget: '9K+' } },
  { id: 'p23', name: 'Rina', age: 27, city: '東涌', occupation: '旅遊博主', tagline: '旅行與攝影', bio: '全職旅遊博主，去過 40 個國家。相信最好的紀念品是回憶。尋找一個也願意出發的人。', cover: img('p23'), photos: [img('p23')], tags: ['旅行', '攝影', '露營', '潛水', '寫作'], verified: true, stats: { lifestyle: '奢華', budget: '14K+' } },
  { id: 'p24', name: 'Ayame', age: 25, city: '銅鑼灣', occupation: '調香師', tagline: '香氣與美學', bio: '為品牌調製香水，相信氣味是記憶的鑰匙。週末逛花市、收集老香水瓶。理想約會是一起聞一場雨。', cover: img('p24'), photos: [img('p24')], tags: ['香水', '花藝', '古董', '詩', '法式'], verified: false, stats: { lifestyle: '奢華', budget: '10K+' } },
  { id: 'p25', name: 'Koharu', age: 31, city: '香港大學', occupation: '大學講師', tagline: '文學與咖啡', bio: '教近代文學，研究女性書寫。喜歡圖書館的氣味與深夜的咖啡。尋找一段能深度對話的關係。', cover: img('p25'), photos: [img('p25')], tags: ['文學', '咖啡', '電影', '古典樂', '京都'], verified: true, stats: { lifestyle: '文青', budget: '13K+' } },
  { id: 'p26', name: 'Shiori', age: 26, city: '粉嶺', occupation: '園藝師', tagline: '植物與自然', bio: '在植物園工作，週末經營自己的小溫室。相信慢就是快。期待一段一起種點什麼的關係。', cover: img('p26'), photos: [img('p26')], tags: ['植物', '溫室', '行山', '素食', '陶藝'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p27', name: 'Hinata', age: 23, city: '將軍澳', occupation: '偶像練習生', tagline: '唱歌與舞台', bio: '在娛樂公司受訓三年，夢想站上紅館。生活是練習與等待。尋找一個相信我、也讓我相信的人。', cover: img('p27'), photos: [img('p27')], tags: ['唱歌', '舞蹈', '舞台', '時尚', '甜品'], verified: false, stats: { lifestyle: '高端', budget: '6K+' } },
  { id: 'p28', name: 'Asuka', age: 30, city: '奧運', occupation: '物理治療師', tagline: '運動與康復', bio: '在運動康復診所工作，幫運動員重返賽場。週末教跑步班。期待一段健康、一起向前跑的關係。', cover: img('p28'), photos: [img('p28')], tags: ['物理治療', '跑步', '健身', '健康飲食', '行山'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p29', name: 'Kanna', age: 28, city: '火炭', occupation: '陶藝家', tagline: '手作與慢活', bio: '在火炭工作室做陶藝，辦過三次個展。相信手作的溫度。理想約會是一起捏一個碗。', cover: img('p29'), photos: [img('p29')], tags: ['陶藝', '手作', '茶道', '素食', '貓'], verified: true, stats: { lifestyle: '文青', budget: '7K+' } },
  { id: 'p30', name: 'Fumiko', age: 33, city: '九龍塘', occupation: '翻譯員', tagline: '語言與文學', bio: '日英中三語翻譯，譯過十本小說。享受文字的精準與曖昧。尋找一段安靜、彼此理解的關係。', cover: img('p30'), photos: [img('p30')], tags: ['翻譯', '文學', '紅酒', '歌劇', '旅行'], verified: true, stats: { lifestyle: '奢華', budget: '16K+' } },
  { id: 'p31', name: 'Chiho', age: 25, city: '西貢', occupation: '潛水教練', tagline: '海洋與冒險', bio: 'PADI 教練，最愛西貢海底的珊瑚。週末帶學員下水。期待一段不怕深、也敢一起冒險的關係。', cover: img('p31'), photos: [img('p31')], tags: ['潛水', '海洋', '衝浪', '旅行', '攝影'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
  { id: 'p32', name: 'Nazuna', age: 27, city: '大坑', occupation: '麵包師', tagline: '烘焙與清晨', bio: '凌晨四點開工的麵包師，最愛看客人咬下第一口。週末睡到中午。尋找一個懂清晨與麵包香的人。', cover: img('p32'), photos: [img('p32')], tags: ['烘焙', '咖啡', '清晨', '單車', '爵士'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p33', name: 'Sayuri', age: 29, city: '紅磡', occupation: '鋼琴家', tagline: '音樂與演出', bio: '交響樂團鋼琴手，巡演過歐亞。舞台之外愛一個人煮麵。期待一段懂休止符的關係。', cover: img('p33'), photos: [img('p33')], tags: ['鋼琴', '古典樂', '歌劇', '紅酒', '巴黎'], verified: true, stats: { lifestyle: '奢華', budget: '19K+' } },
  { id: 'p34', name: 'Wakana', age: 24, city: '黃竹坑', occupation: '時尚模特', tagline: '街頭與攝影', bio: '街頭風模特，常出現在南區的塗鴉牆前。享受被拍的瞬間。尋找一個也敢穿、敢活的人。', cover: img('p34'), photos: [img('p34')], tags: ['時尚', '街拍', '滑板', '音樂節', '咖啡'], verified: false, stats: { lifestyle: '文青', budget: '8K+' } },
  { id: 'p35', name: 'Azumi', age: 32, city: '康城', occupation: '營養師', tagline: '健康與身心', bio: '註冊營養師，教人吃出平衡。自己最愛綠色果昔與海邊散步。期待一段一起好好吃飯的關係。', cover: img('p35'), photos: [img('p35')], tags: ['營養', '果昔', '瑜伽', '行山', '素食'], verified: true, stats: { lifestyle: '高端', budget: '11K+' } },
  { id: 'p36', name: 'Emiri', age: 26, city: '太子', occupation: '花店店主', tagline: '花藝與日常', bio: '在花墟開花店，相信花是日常的詩。週末辦花藝工作坊。理想約會是一起逛花市、回家插一瓶。', cover: img('p36'), photos: [img('p36')], tags: ['花藝', '花店', '咖啡', '甜點', '攝影'], verified: false, stats: { lifestyle: '文青', budget: '6K+' } },
  { id: 'p37', name: 'Ruka', age: 23, city: '深水埗', occupation: '咖啡師', tagline: '拉花與音樂', bio: '在獨立咖啡店做吧台，拉花是我的簽名。下班玩 bass、逛唱片行。尋找一個也懂深夜咖啡的人。', cover: img('p37'), photos: [img('p37')], tags: ['咖啡', '拉花', '音樂', '黑膠', '貓'], verified: false, stats: { lifestyle: '簡約', budget: '4K+' } },
  { id: 'p38', name: 'Shino', age: 30, city: '佐敦', occupation: '中醫師', tagline: '針灸與養生', bio: '註冊中醫，擅長針灸與養生。相信身體是時間的記錄。期待一段慢條理、彼此調理的關係。', cover: img('p38'), photos: [img('p38')], tags: ['中醫', '針灸', '養生', '太極', '茶道'], verified: true, stats: { lifestyle: '高端', budget: '13K+' } },
  { id: 'p39', name: 'Tsumugi', age: 28, city: '鑽石山', occupation: '和服模特', tagline: '傳統與美學', bio: '兼職和服模特，志業是日本傳統文化。週末在志蓮淨苑散步。尋找一個也懂靜與美的人。', cover: img('p39'), photos: [img('p39')], tags: ['和服', '傳統', '茶道', '紅葉', '京都'], verified: true, stats: { lifestyle: '奢華', budget: '15K+' } },
  { id: 'p40', name: 'Suzu', age: 22, city: '大埔', occupation: '美術學生', tagline: '繪畫與公園', bio: '在讀美術系，最愛在大埔海濱公園畫水彩。相信創作是最好的傾訴。期待一段一起安靜看光的關係。', cover: img('p40'), photos: [img('p40')], tags: ['繪畫', '水彩', '公園', '貓', '咖啡'], verified: false, stats: { lifestyle: '簡約', budget: '3K+' } },
  { id: 'p41', name: 'Akane', age: 27, city: '尖沙咀', occupation: '壽司師傅', tagline: '江戶前與清酒', bio: '在壽司店做板前，是店裡少見的女師傅。享受刀工的精準與節奏。尋找一個也懂職人精神的人。', cover: img('p41'), photos: [img('p41')], tags: ['壽司', '清酒', '職人', '旅行', '爵士'], verified: true, stats: { lifestyle: '高端', budget: '12K+' } },
  { id: 'p42', name: 'Riko', age: 26, city: '九龍塘', occupation: '網球手', tagline: '運動與陽光', bio: '半職業網球手，週末教小朋友打球。最愛陽光與流汗的痛快。期待一段健康、一起出汗的關係。', cover: img('p42'), photos: [img('p42')], tags: ['網球', '運動', '陽光', '健康', '旅行'], verified: false, stats: { lifestyle: '高端', budget: '9K+' } },
  { id: 'p43', name: 'Yume', age: 29, city: '黃竹坑', occupation: '珠寶設計師', tagline: '寶石與手作', bio: '在工作室做高訂珠寶，每件都是獨一無二。相信細節是愛。理想約會是一起挑一顆石頭。', cover: img('p43'), photos: [img('p43')], tags: ['珠寶', '寶石', '手作', '美術', '紅酒'], verified: true, stats: { lifestyle: '奢華', budget: '17K+' } },
  { id: 'p44', name: 'Hinako', age: 24, city: '將軍澳', occupation: '牙齒衛生員', tagline: '笑容與健康', bio: '在牙科診所工作，最愛看見客人自信笑。下班愛逛烘焙材料店。尋找一個也愛笑的人。', cover: img('p44'), photos: [img('p44')], tags: ['牙科', '笑容', '烘焙', '貓', '行山'], verified: false, stats: { lifestyle: '簡約', budget: '5K+' } },
]

export const FILTERS = ['全部', '奢華', '高端', '文青', '頂級', '簡約']
